# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-07 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100, verbose_name='First Name')),
                ('lastName', models.CharField(max_length=100, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('contactNo', models.CharField(max_length=15, verbose_name='Contact no')),
                ('address1', models.CharField(max_length=200, verbose_name='Address Line 1')),
                ('address2', models.CharField(max_length=200, null=True, verbose_name='Address Line 2')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('deviceId', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('deviceStatus', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Inactive', max_length=100)),
                ('deviceContactNo', models.CharField(max_length=15, null=True, verbose_name='Active Cell no for Device')),
                ('deviceAddress1', models.CharField(max_length=200, null=True, verbose_name='Address Line 1')),
                ('deviceAddress2', models.CharField(max_length=200, null=True, verbose_name='Address Line 2')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='devices',
            field=models.ManyToManyField(to='control.Device'),
        ),
    ]
