# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-07 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='deviceAddress1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Address Line 1'),
        ),
        migrations.AlterField(
            model_name='device',
            name='deviceAddress2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Address Line 2'),
        ),
        migrations.AlterField(
            model_name='device',
            name='deviceContactNo',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Active Cell no for Device'),
        ),
    ]
