# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-08 10:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_auto_20170907_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='TankStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tankStatus', models.CharField(choices=[('Empty', 'E'), ('Full', 'F')], default='Empty', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='notificationCellNo',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Cell no for Notification'),
        ),
        migrations.AddField(
            model_name='tankstatus',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.Device'),
        ),
    ]
