# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-08 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_auto_20170908_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='deviceContactNo',
            field=models.CharField(max_length=15, verbose_name='Active Cell no for Device'),
        ),
    ]
