# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-08 23:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0004_auto_20170908_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThirdPartyQueue',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='control.Device')),
            ],
        ),
    ]
