# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-09 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0005_thirdpartyqueue'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThirdPartyCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('contactNo', models.CharField(max_length=15, verbose_name='Contact No')),
                ('address1', models.CharField(max_length=200, verbose_name='Address Line 1')),
                ('address2', models.CharField(blank=True, max_length=200, null=True, verbose_name='Address Line 2')),
            ],
        ),
    ]
